Output errors to stderr

diff --git a/SOURCES/logcat b/SOURCES/logcat
--- a/SOURCES/logcat
+++ b/SOURCES/logcat
@@ -3,7 +3,7 @@
 ########################################################################################
 
 APP="LogCat"
-VER="2.0.0"
+VER="2.0.1"
 
 ########################################################################################
 
@@ -12,48 +12,31 @@ BOLD=1
 UNLN=4
 RED=31
 GREEN=32
-BROWN=33
+YELLOW=33
 BLUE=34
 MAG=35
 CYAN=36
 GREY=37
 DARK=90
 
-CL_NORM="\e[${NORM}m"
-CL_BOLD="\e[${BOLD}m"
-CL_UNLN="\e[${UNLN}m"
-CL_RED="\e[${RED}m"
-CL_GREEN="\e[${GREEN}m"
-CL_BROWN="\e[${BROWN}m"
-CL_BLUE="\e[${BLUE}m"
-CL_MAG="\e[${MAG}m"
-CL_CYAN="\e[${CYAN}m"
-CL_GREY="\e[${GREY}m"
-CL_DARK="\e[${DARK}m"
-CL_BL_RED="\e[${RED};1m"
-CL_BL_GREEN="\e[${GREEN};1m"
-CL_BL_BROWN="\e[${BROWN};1m"
-CL_BL_BLUE="\e[${BLUE};1m"
-CL_BL_MAG="\e[${MAG};1m"
-CL_BL_CYAN="\e[${CYAN};1m"
-CL_BL_GREY="\e[${GREY};1m"
-CL_BL_DARK="\e[${DARK};1m"
-CL_UL_RED="\e[${RED};4m"
-CL_UL_GREEN="\e[${GREEN};4m"
-CL_UL_BROWN="\e[${BROWN};4m"
-CL_UL_BLUE="\e[${BLUE};4m"
-CL_UL_MAG="\e[${MAG};4m"
-CL_UL_CYAN="\e[${CYAN};4m"
-CL_UL_GREY="\e[${GREY};4m"
-CL_UL_DARK="\e[${DARK};4m"
-CL_BG_RED="\e[${RED};7m"
-CL_BG_GREEN="\e[${GREEN};7m"
-CL_BG_BROWN="\e[${BROWN};7m"
-CL_BG_BLUE="\e[${BLUE};7m"
-CL_BG_MAG="\e[${MAG};7m"
-CL_BG_CYAN="\e[${CYAN};7m"
-CL_BG_GREY="\e[${GREY};7m"
-CL_BG_DARK="\e[${DARK};7m"
+CL_NORM="\e[0m"
+CL_BOLD="\e[0;${BOLD};49m"
+CL_UNLN="\e[0;${UNLN};49m"
+CL_RED="\e[0;${RED};49m"
+CL_GREEN="\e[0;${GREEN};49m"
+CL_YELLOW="\e[0;${YELLOW};49m"
+CL_BLUE="\e[0;${BLUE};49m"
+CL_MAG="\e[0;${MAG};49m"
+CL_CYAN="\e[0;${CYAN};49m"
+CL_GREY="\e[0;${GREY};49m"
+CL_DARK="\e[0;${DARK};49m"
+CL_BL_RED="\e[1;${RED};49m"
+CL_BL_GREEN="\e[1;${GREEN};49m"
+CL_BL_YELLOW="\e[1;${YELLOW};49m"
+CL_BL_BLUE="\e[1;${BLUE};49m"
+CL_BL_MAG="\e[1;${MAG};49m"
+CL_BL_CYAN="\e[1;${CYAN};49m"
+CL_BL_GREY="\e[1;${GREY};49m"
 
 ########################################################################################
 
@@ -73,23 +56,21 @@ SEP_SYMBOL="-"
 
 main() {
   if [[ ! -t 1 || -n "$no_colors" ]] ; then
-    unset NORM BOLD UNLN RED GREEN BROWN BLUE MAG CYAN GREY DARK
-    unset CL_NORM CL_BOLD CL_UNLN CL_RED CL_GREEN CL_BROWN CL_BLUE CL_MAG CL_CYAN CL_GREY CL_DARK
-    unset CL_BL_RED CL_BL_GREEN CL_BL_BROWN CL_BL_BLUE CL_BL_MAG CL_BL_CYAN CL_BL_GREY CL_BL_DARK
-    unset CL_UL_RED CL_UL_GREEN CL_UL_BROWN CL_UL_BLUE CL_UL_MAG CL_UL_CYAN CL_UL_GREY CL_UL_DARK
-    unset CL_BG_RED CL_BG_GREEN CL_BG_BROWN CL_BG_BLUE CL_BG_MAG CL_BG_CYAN CL_BG_GREY CL_BG_DARK
+    unset NORM BOLD UNLN RED GREEN YELLOW BLUE MAG CYAN GREY DARK
+    unset CL_NORM CL_BOLD CL_UNLN CL_RED CL_GREEN CL_YELLOW CL_BLUE CL_MAG CL_CYAN CL_GREY CL_DARK
+    unset CL_BL_RED CL_BL_GREEN CL_BL_YELLOW CL_BL_BLUE CL_BL_MAG CL_BL_CYAN CL_BL_GREY CL_BL_DARK
   fi
 
   [[ $version || $ver ]] && about && exit 0
   [[ $# -eq 0 || $usage || $help ]] && usage && exit 0
 
   if [[ ! -f $CONF || ! -r $CONF ]] ; then
-    show "Error! Configuration file does not exist or is not readable." $RED
+    error "Error! Configuration file does not exist or is not readable." $RED
     exit 1
   fi
 
   if [[ ! -s $CONF ]] ; then
-    show "Error! Configuration file is empty." $BROWN
+    error "Error! Configuration file is empty." $YELLOW
     exit 0
   fi
 
@@ -104,8 +85,15 @@ main() {
   for file in "$@" ; do
     [[ -d $file ]] && continue
 
-    [[ ! -e $file && ! $ignore_errors ]] && show "Can't read file <$file> - file does not exist." $RED && continue
-    [[ ! -r $file && ! $ignore_errors ]] && show "Can't read file <$file> - file is not readable." $RED && continue
+    if [[ ! -e $file && ! $ignore_errors ]] ; then
+      error "Can't read file ${CL_BL_RED}${file}${CL_RED} - file does not exist" $RED
+      continue
+    fi
+
+    if [[ ! -r $file && ! $ignore_errors ]] ; then
+      error "Can't read file ${CL_BL_RED}${file}${CL_RED} - file is not readable" $RED
+      continue
+    fi
 
     [[ ! -s $file ]] && continue
 
@@ -127,7 +115,9 @@ main() {
         fi
       done < <(grep -Pv '^[ ]*(#(?!\!)|[ ]*$)' $CONF)
 
-      [[ ! $is_file_readed && ! $ignore_errors ]] && show "Can't read file <$file> - file reading is not allowed." $RED
+      if [[ ! $is_file_readed && ! $ignore_errors ]] ; then
+        error "Can't read file ${CL_BL_RED}${file}${CL_RED} - file reading is not allowed" $RED
+      fi
     fi
   done
 
@@ -149,31 +139,31 @@ readFile() {
 
   if [[ "$ext" == "gz" ]] ; then
     if ! checkDeps "gzip" ; then
-      show "Can't read file $file - gzip is not installed." $RED
+      error "Can't read file ${CL_BL_RED}${file}${CL_RED} - gzip is not installed" $RED
     else
       app="zcat"
     fi
   elif [[ "$ext" == "bz" ]] ; then
     if ! checkDeps "bzip2" ; then
-      show "Can't read file $file - zcat is not installed." $RED
+      error "Can't read file ${CL_BL_RED}${file}${CL_RED} - zcat is not installed" $RED
     else
       app="bzcat"
     fi
   elif [[ "$ext" == "7z" ]] ; then
     if ! checkDeps "7zcat" ; then
-      show "Can't read file $file - 7zcat is not installed." $RED
+      error "Can't read file ${CL_BL_RED}${file}${CL_RED} - 7zcat is not installed" $RED
     else
       app="7zcat"
     fi
   elif [[ "$ext" == "xz" ]] ; then
     if ! checkDeps "xz" ; then
-      show "Can't read file $file - xz is not installed." $RED
+      error "Can't read file ${CL_BL_RED}${file}${CL_RED} - xz is not installed" $RED
     else
       app="xzcat"
     fi
   elif [[ "$ext" == "lz" ]] ; then
     if ! checkDeps "xz" ; then
-      show "Can't read file $file - xz is not installed." $RED
+      error "Can't read file ${CL_BL_RED}${file}${CL_RED} - xz is not installed" $RED
     else
       app="lzcat"
     fi
@@ -270,6 +260,17 @@ show() {
   fi
 }
 
+# Print error message
+#
+# 1: Message (String)
+# 2: Message color (Number) [Optional]
+#
+# Code: No
+# Echo: No
+error() {
+  show "$@" 1>&2
+}
+
 # Print usage info
 #
 # Code: No
@@ -333,7 +334,7 @@ about() {
 # Code: No
 # Echo: No
 showArgWarn() {
-  show "Unknown argument $1." $RED
+  error "Unknown argument $1" $RED
   exit 1
 }
 
